<a href="https://colab.research.google.com/github/krishnagoje/100-pandas-puzzles/blob/improvements/Data_Science_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

fruits = ['butter', 'almong', 'chicken']
days = ['mon', 'tue', 'wed','thur','fri']

v = 49

values = np.random.randint(10,50,15).reshape(5,3)
values2 = np.random.randint(1,5,3).reshape(3,1)

df = pd.DataFrame(data = values, columns=fruits, index=days)

df['total'] = df.dot(values2)
# df, values2

# print('the data is {}'.format(df[2,4]))
df

In [0]:
# Arrays's

In [0]:
from google.colab import drive
drive.mount('/content/drive')

# Arrays

In [0]:
arr = np.array([2,3,4,5,6,7])
arr*2
arr[3]
arr[3] = 33
arr

array([ 2,  3,  4, 33,  6,  7])

In [0]:
arr[2:]
arr.argmax()
arr.argmin()
arr[5] = 22
arr

# Tuples


In [0]:
tup = (1, 2, 3, 4, 5, 6, 7)
for i in tup:
  print(i, i*2)
"The length of tuple is " + str(len(tup))

tup1 = (4, 5, 6, 7, 8, 9)

t3 = tup1 + tup
t4 = tup > tup1


t4.count(1)

# Operations on String

In [0]:
name = 'Krishna'
print("capatalise",name.capitalize())
print("upper",name.upper())
print("Center",name.center(15))
print("endswith",name.endswith('a'))
print("startswith",name.startswith('a'))
print("find",name.find('kr',0,4))
print("Replace",name.replace('K',"KK"))
print("sli")



# Factorial

In [0]:
num = 5
fact = 1

for i in range(1,num+1):
  fact = fact * i
print(fact)

120


In [0]:
# List

lst = [1, 2, 4, 4, 5,6,6,7,7,8,9,0]
# lst.sort()
# lst.reverse()
# lst.append(23)
lst.pop(2)
lst

[1, 2, 4, 5, 6, 6, 7, 7, 8, 9, 0]

In [0]:
dic = {'k1': 123, "k2": 500, "k3":[10,20,30], 'k4':{'a':43}}
# dic['k4']['a']

for i, j in dic.items():
  print(i, type(j))

# List


In [0]:
lst = 'abcdef'
lst = list(lst)
lst[0:3]

['a', 'b', 'c']

In [0]:
loc = 'Shp'

if loc == 'Shop':
  print("This is Shop")
elif loc == "Store":
  print("This is Store")
elif loc == "Bank":
  print("This is Bank")
else:
  print("Enter correct String")

Enter correct String


In [0]:
lst = []
for i in range(2,100):
  if i%2==0 and i%3==0:
    lst.append(i)

lst

[6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]

In [0]:
name = 'Krishna'

for i in name:
  print(i)

In [0]:
my_list = [(1,3,4),(4,5,6),(6,7,8)]
for a, b, c in my_list:
  print(c)

4
6
8


In [0]:
dic = {'k1': 123, "k2": 500, "k3":20, 'k4':43}

for i in dic.values():
  print(i)


In [0]:
name = "Krishna Goje"

for i in name:
  print(i)
  if i == 'a':
    continue

In [0]:
word = 'abcde'

for index, i in enumerate(word):
  print(i)

In [0]:
name = list('krishna')
s_name = list('goje')
t = zip(name, s_name)
for i, j in t:
  print(i, j)

In [0]:
import numpy as np
np.random.shuffle(name)
name

In [0]:
# sqr = [ x*x for x in range(0,20) if x%2==0]
sqr = [ x*x if x%2==0 else "En" for x in range(0,10)]

sqr

In [0]:
sqr2 = [x*y for x in range(10,16,2) for y in range(20,40,2)]
sqr2


In [0]:
for num in range(1,100):
  if num % 5 == 0 and num % 3 == 0:
    print(num ," fiz buz")
  elif num % 3 == 0:
    print(num ," fiz")
  elif num % 5 == 0:
    print(num ," buz")

In [0]:
def animal_check(string):
  if 'dog' in string.lower():
    return True
  else:
    return False

animal_check("og is favourite animal")

In [0]:
def animal_check2(string):
  return 'dog' in string.lower()

animal_check2("dog is my favourite")

In [0]:
v = 'aeiou'
def vowel_check(string):
  if string[0] in v:
    return string + 'ay'
  else:
    return string[1:] + string[0] + 'ay'

vowel_check("aKrishna") 

In [0]:
def check(*args):
  return (sum(args))

final = check(15,20)
final

35

In [0]:
def check2(**kwargs):
  if 'fruit' in kwargs:
    print("my fruit of choince is {}".format(kwargs['fruit']))

check2(fruit="Mango")

my fruit of choince is Mango


In [0]:
def small(a,b):
  if a<b:
    return a
  else:
    return b
small(2, 4)

2

In [0]:
name = "My name is Krishna"
name[::-1]

In [0]:
import numpy as np
arr = np.array([1,2,3,3,5,6,7])

def test(string):
  for i in range(0,len(string)-1):
    if arr[i] == arr[i+1] == 3:
      return True
  return False

test(arr)

In [0]:
name = "Krishna"
result = ""

for i in name:
  result =  i*3
print(result)

aaa


In [0]:
import numpy as np


In [8]:
np.arange(0,50).reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [24]:
test = np.linspace(2, 50, 50).reshape(10,5)
print(test)
# print("Max", test.max())
# print("Min", test.min())
# print("argMax", test.argmax())
# print("argMin", test.argmin())
# print("shape", test.shape)
# print("slice 3:5", test[3:5])



[[ 2.          2.97959184  3.95918367  4.93877551  5.91836735]
 [ 6.89795918  7.87755102  8.85714286  9.83673469 10.81632653]
 [11.79591837 12.7755102  13.75510204 14.73469388 15.71428571]
 [16.69387755 17.67346939 18.65306122 19.63265306 20.6122449 ]
 [21.59183673 22.57142857 23.55102041 24.53061224 25.51020408]
 [26.48979592 27.46938776 28.44897959 29.42857143 30.40816327]
 [31.3877551  32.36734694 33.34693878 34.32653061 35.30612245]
 [36.28571429 37.26530612 38.24489796 39.2244898  40.20408163]
 [41.18367347 42.16326531 43.14285714 44.12244898 45.10204082]
 [46.08163265 47.06122449 48.04081633 49.02040816 50.        ]]


In [25]:
test[2:7,1:3]

array([[12.7755102 , 13.75510204],
       [17.67346939, 18.65306122],
       [22.57142857, 23.55102041],
       [27.46938776, 28.44897959],
       [32.36734694, 33.34693878]])

In [43]:
test[test>15]
test.cumsum(axis = 1)
t2 = test.view
print(t2)

<built-in method view of numpy.ndarray object at 0x7f83a1ed0530>


In [44]:
test

array([[ 2.        ,  2.97959184,  3.95918367,  4.93877551,  5.91836735],
       [ 6.89795918,  7.87755102,  8.85714286,  9.83673469, 10.81632653],
       [11.79591837, 12.7755102 , 13.75510204, 14.73469388, 15.71428571],
       [16.69387755, 17.67346939, 18.65306122, 19.63265306, 20.6122449 ],
       [21.59183673, 22.57142857, 23.55102041, 24.53061224, 25.51020408],
       [26.48979592, 27.46938776, 28.44897959, 29.42857143, 30.40816327],
       [31.3877551 , 32.36734694, 33.34693878, 34.32653061, 35.30612245],
       [36.28571429, 37.26530612, 38.24489796, 39.2244898 , 40.20408163],
       [41.18367347, 42.16326531, 43.14285714, 44.12244898, 45.10204082],
       [46.08163265, 47.06122449, 48.04081633, 49.02040816, 50.        ]])

In [0]:
import pandas as pd

data = pd.DataFrame(data = test, columns = list('abcde'), index = list('0123456789'))
data['total'] = data.sum(axis = 1)
row_sum = pd.DataFrame(data.sum(axis = 0))
row_sum = row_sum.transpose()
data = pd.concat([data, row_sum])
# data.iloc[10:1]
# data.reset_index(drop = True, inplace = True)
new_index = ['0', '1', '2', '3', '4', 'u', '6', '7', '8', '9', 'Total']

# data.loc['2',]

In [0]:
# Delete the row with index 0 (No quotation marks)
data.drop(0, inplace = True)

In [0]:
#Conditional data filtering

data[(data['b']>25) & (data['b']<40)]['c']
data[(data['b']>25) & (data['b']<40)]


#Multiindex Data Frame

In [199]:
import numpy as np

inner = ['a','a','b','b']
outer = [1,2,3,4]

indx = list(zip(inner, outer))
indx = pd.MultiIndex.from_tuples(indx)

df = pd.DataFrame(np.random.randn(4,3),indx, ['x','y','z'])

df.loc['a']
df.loc['a'].loc[2]['x']
df.loc['b'].loc[4]['x']
df.loc['b'].loc[4]['y']

#Assinging Names to Index Columns
df.index.names = ['Group','Index']
df

x         y         z
Group Index                              
a     1      0.790471 -0.812181  1.240681
      2      2.090876 -0.940319  0.411711
b     3      0.755793  1.368298 -0.202182
      4     -0.758075 -1.857924 -0.016208